trigger:
- master

variables:

  functionAppName: 'func-demo-function-app'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build + Deploy

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UseDotNet@2
      displayName: "Specify dot net version"
      inputs:
        version: '8.0.200'
    - task: DotNetCoreCLI@2
      displayName: "build and publish"
      inputs:
        command: publish
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/fn_publish_output'
        projects: '$(System.DefaultWorkingDirectory)/src/CustomerOnboarding.FunctionApp/CustomerOnboarding.FunctionApp.csproj'
        publishWebProjects: false
        modifyOutputPath: false
        zipAfterPublish: false
    - task: ArchiveFiles@2
      displayName: "Archive files"
      inputs:
        rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/fn_publish_output"
        includeRootFolder: false
        archiveFile: "$(Build.ArtifactStagingDirectory)/fn_zip/build$(Build.BuildId).zip"
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/fn_zip/build$(Build.BuildId).zip'
        artifactName: 'function_app'
    - task: AzureFunctionApp@2
      inputs:
        connectedServiceNameARM: 'az-free-sub-service-connection'
        appType: 'functionApp'
        appName: '$(functionAppName)'
        package: '$(Build.ArtifactStagingDirectory)/fn_zip/build$(Build.BuildId).zip'
        deploymentMethod: 'auto'